services:
  - type: web
    name: projeto-cloud-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        sync: false # você informa o valor no painel do Render (connection string do Neon)
